import React from 'react';

export const TermsAndConditions: React.FC = () => {
  return (
    <div className="flex-1 p-6 md:p-10 max-w-5xl mx-auto space-y-8 text-slate-200">
      {/* Header Banner */}
      <div className="border-b border-slate-800 pb-6">
        <div className="flex items-center gap-2 text-xs text-purple-400 font-semibold uppercase tracking-wider mb-2">
          <span>Legal Framework</span>
          <span>•</span>
          <span>Open Science & Data Attribution</span>
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
          Terms & Conditions of Service
        </h1>
        <p className="text-slate-400 text-sm mt-2">
          Effective Date: September 19, 2026 | Governing Law: Republic of India
        </p>
      </div>

      {/* Advisory Alert */}
      <div className="p-4 rounded-2xl bg-amber-950/20 border border-amber-800/40 text-xs text-amber-200 leading-relaxed flex items-start gap-3">
        <span className="text-xl" aria-hidden="true">⚠️</span>
        <div>
          <strong className="font-semibold block text-amber-100 text-sm">Scientific & Advisory Disclaimers</strong>
          AeroVision models utilize satellite remote sensing column measurements and statistical neural networks to infer surface concentrations. Values displayed are intended for environmental research, policy planning, and public health awareness, and do not supersede statutory emergency advisories issued by national disaster authorities.
        </div>
      </div>

      {/* Terms Content */}
      <div className="space-y-6 text-sm leading-relaxed text-slate-300">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or utilizing the AeroVision atmospheric telemetry portal, APIs, research documents, or visual dashboards, you acknowledge that you have read, understood, and agreed to be legally bound by these Terms and Conditions. If you disagree with any portion of these terms, you must terminate platform usage immediately.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">2. Intellectual Property & Attribution</h2>
          <p>
            The visualization software, geospatial rendering pipelines, and ML prediction architecture of Project AeroVision are protected under international copyright and open scientific research licenses. When referencing data, maps, or reports generated by AeroVision:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Citation Format:</strong> Cite as: <em>&quot;Project AeroVision: National-Scale Surface AQI & HCHO Hotspot Intelligence Platform (2026)&quot;</em>.</li>
            <li><strong>Source Attribution:</strong> Acknowledge respective raw satellite providers including ISRO SAC, ESA Copernicus Sentinel-5P, NASA FIRMS, and CPCB India.</li>
            <li><strong>Commercial Redistribution:</strong> Commercial syndication of raw API feeds without prior written authorization is strictly prohibited.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">3. Acceptable Use Policy</h2>
          <p>
            You agree to interact with the platform and API endpoints in a responsible manner:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Do not execute automated scripts, high-frequency crawlers, or scraping loops that degrade server capacity (exceeding 60 requests per minute).</li>
            <li>Do not attempt to probe, scan, or compromise backend endpoints, database instances, or geospatial microservices.</li>
            <li>Do not misrepresent AeroVision model predictions as official executive directives from environmental ministries.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">4. Warranty Disclaimer & Model Precision</h2>
          <p>
            While AeroVision applies rigorous validation against CPCB continuous ambient air quality monitoring stations (CAAQMS), all data, prognostic trajectories, and AI-synthesized summaries are provided <strong>&quot;AS IS&quot; and &quot;AS AVAILABLE&quot;</strong>. Atmospheric satellite measurements may experience localized gaps due to persistent cloud cover, aerosol optical depth saturation, or sensor calibration passes.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">5. Limitation of Liability</h2>
          <p>
            Under no circumstances shall Project AeroVision, research contributors, institutional partners, or data contributors be liable for any direct, indirect, incidental, punitive, or consequential damages resulting from reliance on air quality indices, health exposure scores, or wildfire correlation figures.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">6. Governing Jurisdiction & Dispute Resolution</h2>
          <p>
            These Terms shall be construed and governed in accordance with the substantive laws of the Republic of India. Any legal dispute or proceeding arising out of or related to this platform shall be subject to the exclusive jurisdiction of the competent courts in New Delhi, India.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white">7. Revisions to Terms</h2>
          <p>
            We reserve the right to revise or update these Terms periodically to mirror regulatory adaptations or new satellite constellation integrations. Continued use of the platform constitutes acceptance of amended conditions.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsAndConditions;
